version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    volumes:
      - artifactory5_data:/var/opt/jfrog/artifactory
    ports:
      - 8081:8081

volumes:
  artifactory5_data: